spring:
  application:
    name: quiz
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: quiz-app
  config:
    import: optional:file:.env[.properties]

app:
  jwtSecret: ${JWT_SECRET_KEY}
  jwtExpirationMs: 900000 # 15 dakika
  jwtRefreshExpirationMs: 604800000 # 7 gün

# CORS Configuration
cors:
  allowed-origins: "*"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  exposed-headers: "Authorization"
  max-age: 3600

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    enabled: true
    url: /v3/api-docs
  show-actuator: true
  default-produces-media-type: application/json
  use-fqn: true
  model-and-view-allowed: true
